/**
 * Copyright 2011 Niall Gallagher
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * [private api] This package contains machine-generated Google Protocol Buffer (protobuf) classes for encoding messages
 * to/from binary.
 * <p/>
 * <b>Classes in this package are auto-generated by Protobuf's {@code protoc} compiler in the Maven compile phase
 * of the build.</b> They will be saved into this package, but in the <b>{@code target/generated-sources/}</b>
 * directory.
 */
package com.googlecode.mobilityrpc.protocol.protobuf;